AWSTemplateFormatVersion: "2010-09-09"
Description: Build EC2 Instance

Parameters:

#EC2
  EC2InstanceType:
    Description: Instance type to launch EC2 Indexer instances.
    Type: String
    Default: c5.4xlarge
    AllowedValues: [ c5.4xlarge ,c5.9xlarge, t2.micro ]
    
#Select VPC
  VPCID:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC where the EC2 instances will be created
    ConstraintDescription: must be an existing VPC

#Select Subnet1
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select subnet for Instance
    ConstraintDescription: must be an existing subnet
    
#AMI selection
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2    
    
Resources:
    
#EC2 Creation
  EC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 5
            Encrypted: True
      NetworkInterfaces:
          SubnetId: !Ref Subnet
          
      ImageId: !Ref LatestAmiId
      AvailabilityZone: us-east-1a
      InstanceType: !Ref EC2InstanceType
